package kostal

// from the kostal documentation BA_KOSTAL-Interface-description-MODBUS-TCP_SunSpec_Hybrid.pdf
func registers() []Register {
	return []Register{
		{
			Addr:        0x2,
			Description: "MODBUS Enable",
			format:      "Bool",
			length:      0x1,
			InfluxField: "modbus_enable",
			Include:     false,
		},
		{
			Addr:        0x4,
			Description: "MODBUS Unit-ID",
			format:      "U16",
			length:      0x1,
			InfluxField: "modbus_unit_id",
			Include:     false,
		},
		{
			Addr:        0x5,
			Description: "MODBUS Byte Order Note",
			format:      "U16",
			length:      0x1,
			InfluxField: "modbus_byte_order_note",
			Include:     false,
		},
		{
			Addr:        0x6,
			Description: "Inverter article number",
			format:      "String",
			length:      0x8,
			InfluxField: "inverter_article_number",
			Include:     false,
		},
		{
			Addr:        0xe,
			Description: "Inverter serial number",
			format:      "String",
			length:      0x8,
			InfluxField: "inverter_serial_number",
			Include:     false,
		},
		{
			Addr:        0x1e,
			Description: "Number of bidirectional converter",
			format:      "U16",
			length:      0x1,
			InfluxField: "number_of_bidirectional_converter",
			Include:     false,
		},
		{
			Addr:        0x20,
			Description: "Number of AC phases",
			format:      "U16",
			length:      0x1,
			InfluxField: "number_of_ac_phases",
			Include:     false,
		},
		{
			Addr:        0x22,
			Description: "Number of PV strings",
			format:      "U16",
			length:      0x1,
			InfluxField: "number_of_pv_strings",
			Include:     false,
		},
		{
			Addr:        0x24,
			Description: "Hardware-Version",
			format:      "U16",
			length:      0x2,
			InfluxField: "hardware_version",
			Include:     false,
		},
		{
			Addr:        0x26,
			Description: "Software-Version Maincontroller (MC)",
			format:      "String",
			length:      0x8,
			InfluxField: "software_version_maincontroller",
			Include:     false,
		},
		{
			Addr:        0x2e,
			Description: "Software-Version IO-Controller (IOC)",
			format:      "String",
			length:      0x8,
			InfluxField: "software_version_io_controller",
			Include:     false,
		},
		{
			Addr:        0x36,
			Description: "Power-ID",
			format:      "U16",
			length:      0x2,
			InfluxField: "power_id",
			Include:     false,
		},
		{
			Addr:        0x38,
			Description: "Inverter state",
			format:      "U16",
			length:      0x2,
			InfluxField: "inverter_state",
			Include:     true,
		},
		{
			Addr:        0x62,
			Description: "Temperature of controller PCB",
			format:      "Float",
			length:      0x2,
			InfluxField: "temperature_of_controller_pcb_degc",
			Include:     true,
		},
		{
			Addr:        0x64,
			Description: "Total DC power",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_power_w",
			Include:     true,
		},
		{
			Addr:        0x68,
			Description: "State of energy manager",
			format:      "U32",
			length:      0x2,
			InfluxField: "state_of_energy_manager",
			Include:     true,
		},
		{
			Addr:        0x6a,
			Description: "Home own consumption from battery",
			format:      "Float",
			length:      0x2,
			InfluxField: "home_own_consumption_from_battery_w",
			Include:     false,
		},
		{
			Addr:        0x6c,
			Description: "Home own consumption from grid",
			format:      "Float",
			length:      0x2,
			InfluxField: "home_own_consumption_from_grid_w",
			Include:     false,
		},
		{
			Addr:        0x6e,
			Description: "Total home consumption Battery",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_home_consumption_battery_wh",
			Include:     false,
		},
		{
			Addr:        0x70,
			Description: "Total home consumption Grid",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_home_consumption_grid_wh",
			Include:     false,
		},
		{
			Addr:        0x72,
			Description: "Total home consumption PV",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_home_consumption_pv_wh",
			Include:     false,
		},
		{
			Addr:        0x74,
			Description: "Home own consumption from PV",
			format:      "Float",
			length:      0x2,
			InfluxField: "home_own_consumption_from_pv_w",
			Include:     false,
		},
		{
			Addr:        0x76,
			Description: "Total home consumption",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_home_consumption_wh",
			Include:     false,
		},
		{
			Addr:        0x78,
			Description: "Isolation resistance",
			format:      "Float",
			length:      0x2,
			InfluxField: "isolation_resistance_ohm",
			Include:     false,
		},
		{
			Addr:        0x7a,
			Description: "Power limit from EVU",
			format:      "Float",
			length:      0x2,
			InfluxField: "power_limit_from_evu_percent",
			Include:     false,
		},
		{
			Addr:        0x7c,
			Description: "Total home consumption rate",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_home_consumption_rate_percent",
			Include:     false,
		},
		{
			Addr:        0x90,
			Description: "Worktime",
			format:      "Float",
			length:      0x2,
			InfluxField: "worktime_seconds",
			Include:     true,
		},
		{
			Addr:        0x96,
			Description: "Actual cos φ",
			format:      "Float",
			length:      0x2,
			InfluxField: "actual_cos_phi",
			Include:     true,
		},
		{
			Addr:        0x98,
			Description: "Grid frequency",
			format:      "Float",
			length:      0x2,
			InfluxField: "grid_frequency_hz",
			Include:     true,
		},
		{
			Addr:        0x9a,
			Description: "Current Phase 1",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_phase_1_a",
			Include:     true,
		},
		{
			Addr:        0x9c,
			Description: "Active power Phase 1",
			format:      "Float",
			length:      0x2,
			InfluxField: "active_power_phase_1_w",
			Include:     true,
		},
		{
			Addr:        0x9e,
			Description: "Voltage Phase 1",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_phase_1_v",
			Include:     true,
		},
		{
			Addr:        0xa0,
			Description: "Current Phase 2",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_phase_2_a",
			Include:     true,
		},
		{
			Addr:        0xa2,
			Description: "Active power Phase 2",
			format:      "Float",
			length:      0x2,
			InfluxField: "active_power_phase_2_w",
			Include:     true,
		},
		{
			Addr:        0xa4,
			Description: "Voltage Phase 2",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_phase_2_v",
			Include:     true,
		},
		{
			Addr:        0xa6,
			Description: "Current Phase 3",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_phase_3_a",
			Include:     true,
		},
		{
			Addr:        0xa8,
			Description: "Active power Phase 3",
			format:      "Float",
			length:      0x2,
			InfluxField: "active_power_phase_3_w",
			Include:     true,
		},
		{
			Addr:        0xaa,
			Description: "Voltage Phase 3",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_phase_3_v",
			Include:     true,
		},
		{
			Addr:        0xac,
			Description: "Total AC active power",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_ac_active_power_w",
			Include:     true,
		},
		{
			Addr:        0xae,
			Description: "Total AC reactive power",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_ac_reactive_power",
			Include:     true,
		},
		{
			Addr:        0xb2,
			Description: "Total AC apparent power",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_ac_apparent_power_va",
			Include:     true,
		},
		{
			Addr:        0xbe,
			Description: "Battery charge current",
			format:      "Float",
			length:      0x2,
			InfluxField: "battery_charge_current_a",
			Include:     false,
		},
		{
			Addr:        0xc2,
			Description: "Number of battery cycles",
			format:      "Float",
			length:      0x2,
			InfluxField: "number_of_battery_cycles",
			Include:     false,
		},
		{
			Addr:        0xc8,
			Description: "Actual battery charge (-) / discharge (+) current",
			format:      "Float",
			length:      0x2,
			InfluxField: "actual_battery_charge_discharge_current_a",
			Include:     false,
		},
		{
			Addr:        0xca,
			Description: "PSSB fuse state",
			format:      "Float",
			length:      0x2,
			InfluxField: "pssb_fuse_state",
			Include:     false,
		},
		{
			Addr:        0xd0,
			Description: "Battery ready flag",
			format:      "Float",
			length:      0x2,
			InfluxField: "battery_ready_flag",
			Include:     false,
		},
		{
			Addr:        0xd2,
			Description: "Act. state of charge",
			format:      "Float",
			length:      0x2,
			InfluxField: "act_state_of_charge_percent",
			Include:     false,
		},
		{
			Addr:        0xd6,
			Description: "Battery temperature",
			format:      "Float",
			length:      0x2,
			InfluxField: "battery_temperature_degc",
			Include:     false,
		},
		{
			Addr:        0xd8,
			Description: "Battery voltage",
			format:      "Float",
			length:      0x2,
			InfluxField: "battery_voltage_v",
			Include:     false,
		},
		{
			Addr:        0xda,
			Description: "Cos φ (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "cos_phi_powermeter",
			Include:     false,
		},
		{
			Addr:        0xdc,
			Description: "Frequency (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "frequency_powermeter_hz",
			Include:     false,
		},
		{
			Addr:        0xde,
			Description: "Current phase 1 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_phase_1_powermeter_a",
			Include:     false,
		},
		{
			Addr:        0xe0,
			Description: "Active power phase 1 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "active_power_phase_1_powermeter_w",
			Include:     false,
		},
		{
			Addr:        0xe2,
			Description: "Reactive power phase 1 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "reactive_power_phase_1_powermeter",
			Include:     false,
		},
		{
			Addr:        0xe4,
			Description: "Apparent power phase 1 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "apparent_power_phase_1_powermeter_va",
			Include:     false,
		},
		{
			Addr:        0xe6,
			Description: "Voltage phase 1 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_phase_1_powermeter_v",
			Include:     false,
		},
		{
			Addr:        0xe8,
			Description: "Current phase 2 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_phase_2_powermeter_a",
			Include:     false,
		},
		{
			Addr:        0xea,
			Description: "Active power phase 2 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "active_power_phase_2_powermeter_w",
			Include:     false,
		},
		{
			Addr:        0xec,
			Description: "Reactive power phase 2 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "reactive_power_phase_2_powermeter",
			Include:     false,
		},
		{
			Addr:        0xee,
			Description: "Apparent power phase 2 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "apparent_power_phase_2_powermeter_va",
			Include:     false,
		},
		{
			Addr:        0xf0,
			Description: "Voltage phase 2 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_phase_2_powermeter_v",
			Include:     false,
		},
		{
			Addr:        0xf2,
			Description: "Current phase 3 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_phase_3_powermeter_a",
			Include:     false,
		},
		{
			Addr:        0xf4,
			Description: "Active power phase 3 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "active_power_phase_3_powermeter_w",
			Include:     false,
		},
		{
			Addr:        0xf6,
			Description: "Reactive power phase 3 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "reactive_power_phase_3_powermeter",
			Include:     false,
		},
		{
			Addr:        0xf8,
			Description: "Apparent power phase 3 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "apparent_power_phase_3_powermeter_va",
			Include:     false,
		},
		{
			Addr:        0xfa,
			Description: "Voltage phase 3 (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_phase_3_powermeter_v",
			Include:     false,
		},
		{
			Addr:        0xfc,
			Description: "Total active power (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_active_power_powermeter_w",
			Include:     false,
		},
		{
			Addr:        0xfe,
			Description: "Total reactive power (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_reactive_power_powermeter",
			Include:     false,
		},
		{
			Addr:        0x100,
			Description: "Total apparent power (powermeter)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_apparent_power_powermeter_va",
			Include:     false,
		},
		{
			Addr:        0x102,
			Description: "Current DC1",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_dc1_a",
			Include:     true,
		},
		{
			Addr:        0x104,
			Description: "Power DC1",
			format:      "Float",
			length:      0x2,
			InfluxField: "power_dc1_w",
			Include:     true,
		},
		{
			Addr:        0x10a,
			Description: "Voltage DC1",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_dc1_v",
			Include:     true,
		},
		{
			Addr:        0x10c,
			Description: "Current DC2",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_dc2_a",
			Include:     true,
		},
		{
			Addr:        0x10e,
			Description: "Power DC2",
			format:      "Float",
			length:      0x2,
			InfluxField: "power_dc2_w",
			Include:     true,
		},
		{
			Addr:        0x114,
			Description: "Voltage DC2",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_dc2_v",
			Include:     true,
		},
		{
			Addr:        0x116,
			Description: "Current DC3",
			format:      "Float",
			length:      0x2,
			InfluxField: "current_dc3_a",
			Include:     true,
		},
		{
			Addr:        0x118,
			Description: "Power DC3",
			format:      "Float",
			length:      0x2,
			InfluxField: "power_dc3_w",
			Include:     true,
		},
		{
			Addr:        0x11e,
			Description: "Voltage DC3",
			format:      "Float",
			length:      0x2,
			InfluxField: "voltage_dc3_v",
			Include:     true,
		},
		{
			Addr:        0x140,
			Description: "Total yield",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_yield_wh",
			Include:     true,
		},
		{
			Addr:        0x142,
			Description: "Daily yield",
			format:      "Float",
			length:      0x2,
			InfluxField: "daily_yield_wh",
			Include:     true,
		},
		{
			Addr:        0x144,
			Description: "Yearly yield",
			format:      "Float",
			length:      0x2,
			InfluxField: "yearly_yield_wh",
			Include:     true,
		},
		{
			Addr:        0x146,
			Description: "Monthly yield",
			format:      "Float",
			length:      0x2,
			InfluxField: "monthly_yield_wh",
			Include:     true,
		},
		{
			Addr:        0x180,
			Description: "Inverter network name",
			format:      "String",
			length:      0x20,
			InfluxField: "inverter_network_name",
			Include:     false,
		},
		{
			Addr:        0x1a0,
			Description: "IP enable",
			format:      "U16",
			length:      0x1,
			InfluxField: "ip_enable",
			Include:     false,
		},
		{
			Addr:        0x1a2,
			Description: "Manual IP / Auto-IP",
			format:      "U16",
			length:      0x1,
			InfluxField: "manual_ip_auto_ip",
			Include:     false,
		},
		{
			Addr:        0x1a4,
			Description: "IP-address",
			format:      "String",
			length:      0x8,
			InfluxField: "ip_address",
			Include:     false,
		},
		{
			Addr:        0x1ac,
			Description: "IP-subnetmask",
			format:      "String",
			length:      0x8,
			InfluxField: "ip_subnetmask",
			Include:     false,
		},
		{
			Addr:        0x1b4,
			Description: "IP-gateway",
			format:      "String",
			length:      0x8,
			InfluxField: "ip_gateway",
			Include:     false,
		},
		{
			Addr:        0x1bc,
			Description: "IP-auto-DNS",
			format:      "U16",
			length:      0x1,
			InfluxField: "ip_auto_dns",
			Include:     false,
		},
		{
			Addr:        0x1be,
			Description: "IP-DNS1",
			format:      "String",
			length:      0x8,
			InfluxField: "ip_dns1",
			Include:     false,
		},
		{
			Addr:        0x1c6,
			Description: "IP-DNS2",
			format:      "String",
			length:      0x8,
			InfluxField: "ip_dns2",
			Include:     false,
		},
		{
			Addr:        0x200,
			Description: "Battery gross capacity",
			format:      "U32",
			length:      0x2,
			InfluxField: "battery_gross_capacity_ah",
			Include:     false,
		},
		{
			Addr:        0x202,
			Description: "Battery actual SOC",
			format:      "U16",
			length:      0x1,
			InfluxField: "battery_actual_soc_percent",
			Include:     false,
		},
		{
			Addr:        0x203,
			Description: "Firmware Maincontroller (MC)",
			format:      "U32",
			length:      0x2,
			InfluxField: "firmware_maincontroller",
			Include:     false,
		},
		{
			Addr:        0x205,
			Description: "Battery Manufacturer",
			format:      "String",
			length:      0x8,
			InfluxField: "battery_manufacturer",
			Include:     false,
		},
		{
			Addr:        0x20d,
			Description: "Battery Model ID",
			format:      "U32",
			length:      0x2,
			InfluxField: "battery_model_id",
			Include:     false,
		},
		{
			Addr:        0x20f,
			Description: "Battery Serial Number",
			format:      "U32",
			length:      0x2,
			InfluxField: "battery_serial_number",
			Include:     false,
		},
		{
			Addr:        0x211,
			Description: "Work Capacity",
			format:      "U32",
			length:      0x2,
			InfluxField: "work_capacity_wh",
			Include:     false,
		},
		{
			Addr:        0x213,
			Description: "Inverter Max Power",
			format:      "U16",
			length:      0x1,
			InfluxField: "inverter_max_power_w",
			Include:     false,
		},
		{
			Addr:        0x214,
			Description: "Inverter Max Power Scale Factor",
			format:      "-",
			length:      0x1,
			InfluxField: "inverter_max_power_scale_factor",
			Include:     false,
		},
		{
			Addr:        0x215,
			Description: "Active Power Setpoint",
			format:      "U16",
			length:      0x1,
			InfluxField: "active_power_setpoint_percent",
			Include:     false,
		},
		{
			Addr:        0x217,
			Description: "Inverter Manufacturer",
			format:      "String",
			length:      0x10,
			InfluxField: "inverter_manufacturer",
			Include:     false,
		},
		{
			Addr:        0x22f,
			Description: "Inverter Serial Number",
			format:      "String",
			length:      0x10,
			InfluxField: "inverter_serial_number_559",
			Include:     false,
		},
		{
			Addr:        0x23f,
			Description: "Inverter Generation Power (actual)",
			format:      "S16",
			length:      0x1,
			InfluxField: "inverter_generation_power_w",
			Include:     true,
		},
		{
			Addr:        0x240,
			Description: "Power Scale Factor",
			format:      "-",
			length:      0x1,
			InfluxField: "power_scale_factor",
			Include:     false,
		},
		{
			Addr:        0x241,
			Description: "Generation Energy",
			format:      "U32",
			length:      0x2,
			InfluxField: "generation_energy_wh",
			Include:     false,
		},
		{
			Addr:        0x243,
			Description: "Energy Scale Factor",
			format:      "-",
			length:      0x1,
			InfluxField: "energy_scale_factor",
			Include:     false,
		},
		{
			Addr:        0x246,
			Description: "Actual battery charge/discharge power",
			format:      "S16",
			length:      0x1,
			InfluxField: "actual_battery_charge_discharge_power_w",
			Include:     false,
		},
		{
			Addr:        0x247,
			Description: "Reactive Power Setpoint",
			format:      "S16",
			length:      0x1,
			InfluxField: "reactive_power_setpoint_percent",
			Include:     false,
		},
		{
			Addr:        0x249,
			Description: "Delta-cos φ Setpoint",
			format:      "S16",
			length:      0x1,
			InfluxField: "delta_cos_phi_setpoint",
			Include:     false,
		},
		{
			Addr:        0x24a,
			Description: "Battery Firmware",
			format:      "U32",
			length:      0x2,
			InfluxField: "battery_firmware",
			Include:     false,
		},
		{
			Addr:        0x24c,
			Description: "Battery Type",
			format:      "U16",
			length:      0x1,
			InfluxField: "battery_type",
			Include:     false,
		},
		{
			Addr:        0x300,
			Description: "Productname (e.g. PLENTICORE plus)",
			format:      "String",
			length:      0x20,
			InfluxField: "productname",
			Include:     false,
		},
		{
			Addr:        0x320,
			Description: "Power class (e.g. 10)",
			format:      "String",
			length:      0x20,
			InfluxField: "power_class",
			Include:     false,
		},
		{
			Addr:        0x416,
			Description: "Total DC charge energy (DC-side to battery)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_charge_energy_wh",
			Include:     false,
		},
		{
			Addr:        0x418,
			Description: "Total DC discharge energy (DC-side from battery)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_discharge_energy_wh",
			Include:     false,
		},
		{
			Addr:        0x41a,
			Description: "Total AC charge energy (AC-side to battery)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_ac_charge_energy_wh",
			Include:     false,
		},
		{
			Addr:        0x41c,
			Description: "Total AC discharge energy (battery to grid)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_ac_discharge_energy_wh",
			Include:     false,
		},
		{
			Addr:        0x41e,
			Description: "Total AC charge energy (grid to battery)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_ac_charge_energy_wh",
			Include:     false,
		},
		{
			Addr:        0x420,
			Description: "Total DC PV energy (sum of all PV inputs)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_pv_energy_sum_of_all_inputs_wh",
			Include:     false,
		},
		{
			Addr:        0x422,
			Description: "Total DC energy from PV1",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_energy_from_pv1_wh",
			Include:     false,
		},
		{
			Addr:        0x424,
			Description: "Total DC energy from PV2",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_energy_from_pv2_wh",
			Include:     false,
		},
		{
			Addr:        0x426,
			Description: "Total DC energy from PV3",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_energy_from_pv3_wh",
			Include:     false,
		},
		{
			Addr:        0x428,
			Description: "Total energy AC-side to grid",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_energy_ac_side_to_grid_wh",
			Include:     false,
		},
		{
			Addr:        0x42a,
			Description: "Total DC power (sum of all PV inputs)",
			format:      "Float",
			length:      0x2,
			InfluxField: "total_dc_power_sum_of_all_inputs_w",
			Include:     false,
		},
	}
}
